# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  # Root
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 10

  # Apps
  - package-ecosystem: 'npm'
    directory: '/apps/backend'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 10

  - package-ecosystem: 'npm'
    directory: '/apps/frontend'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 10

  # Packages
  - package-ecosystem: 'npm'
    directory: '/packages/api'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/cosmosdb'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/eslint-config'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/jwt'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/schemas'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/strava'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/types'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/typescript-config'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/queue-helpers'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5

  - package-ecosystem: 'npm'
    directory: '/packages/weather'
    schedule:
      interval: 'weekly'
    target-branch: 'main'
    open-pull-requests-limit: 5
