version: "3.8"
services:
  frontend:
    build:
      context: .
      dockerfile: infrastructure/docker/next/Dockerfile
      args:
        APP_NAME: frontend
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    env_file:
      - path: apps/frontend/.env.local
        required: false
  backend:
    build:
      context: .
      dockerfile: infrastructure/docker/nest/Dockerfile
      args:
        APP_NAME: backend
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    env_file:
      - path: apps/backend/.env
        required: true
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    ports:
      - "27017:27017"
    env_file:
      - path: apps/backend/.env
        required: true
volumes:
  mongodb_data:
