version: "3.8"
services:
  frontend:
    image: ghcr.io/joranslingerland/running-frontend:main
    networks:
      - backend_network
    depends_on:
      - mongodb
      - backend
    env_file:
      - path: .env
        required: false
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb:27017
      - NESTJS_URL=http://backend:3001

  backend:
    image: ghcr.io/joranslingerland/running-backend:main
    networks:
      - backend_network
    depends_on:
      - mongodb
    env_file:
      - path: .env
        required: false
    command: >
      /bin/sh -c "
        yarn db:setup &&
        node dist/main.js
      "
    environment:
      - MONGODB_URI=mongodb:27017

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend_network
    env_file:
      - path: .env
        required: false
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  mongodb_data:
networks:
  backend_network:
    driver: bridge
