version: '3.8'
services:
  mongodb:
    build:
      context: .
      dockerfile: infrastructure/docker/mongodb/Dockerfile
    volumes:
      - mongodb_data:/data/db
    ports:
      - '27017:27017'
    env_file:
      - path: infrastructure/db/db.env.local
        required: true
volumes:
  mongodb_data:
