version: "3.8"
services:
  frontend:
    image: ghcr.io/joranslingerland/running-frontend:main
    networks:
      - backend_network
    depends_on:
      - mongodb
      - backend
    env_file:
      - path: .env
        required: false
    ports:
      - "3000:3000"
    environment:
      - API_SHARED_KEY = ${API_SHARED_KEY}
      - NEXT_PUBLIC_STRAVA_CLIENT_ID = ${NEXT_PUBLIC_STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SERCRET = ${STRAVA_CLIENT_SERCRET}
      - STRAVA_DAILY_LIMIT = ${STRAVA_DAILY_LIMIT}
      - STRAVA_15MIN_LIMIT = ${STRAVA_15MIN_LIMIT}
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_URI=mongodb:27017
      - NEXT_PUBLIC_api_key = ${NEXT_PUBLIC_api_key}
      - NEXTAUTH_ADMIN_EMAIL = ${NEXTAUTH_ADMIN_EMAIL}
      - NEXTAUTH_SECRET = ${NEXTAUTH_SECRET}
      - NEXTAUTH_SALT = ${NEXTAUTH_SALT}
      - NEXTAUTH_URL = ${NEXTAUTH_URL}
      - NEXTAUTH_GITHUB_CLIENTID = ${NEXTAUTH_GITHUB_CLIENTID}
      - NEXTAUTH_GITHUB_CLIENTSECRET = ${NEXTAUTH_GITHUB_CLIENTSECRET}
      - NESTJS_URL=http://backend:3001
      - NEXT_PUBLIC_MAPTILERTOKEN = ${NEXT_PUBLIC_MAPTILERTOKEN}

  backend:
    image: ghcr.io/joranslingerland/running-backend:main
    networks:
      - backend_network
    depends_on:
      - mongodb
    env_file:
      - path: .env
        required: false
    command: >
      /bin/sh -c "
        yarn db:setup &&
        node dist/main.js
      "
    environment:
      - API_SHARED_KEY = ${API_SHARED_KEY}
      - NEXT_PUBLIC_STRAVA_CLIENT_ID = ${NEXT_PUBLIC_STRAVA_CLIENT_ID}
      - STRAVA_CLIENT_SERCRET = ${STRAVA_CLIENT_SERCRET}
      - STRAVA_DAILY_LIMIT = ${STRAVA_DAILY_LIMIT}
      - STRAVA_15MIN_LIMIT = ${STRAVA_15MIN_LIMIT}
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_INITDB_ROOT_PASSWORD}
      - MONGODB_URI=mongodb:27017

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend_network
    env_file:
      - path: .env
        required: false
    environment:
      - MONGO_INITDB_ROOT_USERNAME = ${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD = ${MONGO_INITDB_ROOT_PASSWORD}
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 30s
      timeout: 10s
      retries: 3
volumes:
  mongodb_data:
networks:
  backend_network:
    driver: bridge
