name: Build

on: push

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/workflows/actions/setup-node

      - name: Run build
        run: yarn run build
