name: Deploy to Azure

on:
  push:
    branches: ["main", "feature/next-auth"]

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout # Checked out your repository
        uses: actions/checkout@v3

      - name: Setup Node # Installs NodeJS 18
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies # Installs your app dependencies
        run: |
          yarn install

      - name: 'Login to Azure Subscription' # This is required for OIDC authentication to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Next.js app
        run: |
          yarn build
          mv .next/static .next/standalone/.next/static
          # mv public .next/standalone/public
          
      - name: Deploy
        shell: pwsh
        run: |
          $ZIP_FILE_NAME = "./${{ env.FILE_NAME }}.zip"
          zip $ZIP_FILE_NAME ./* .next -qr
        
          write-host "Deploying $ZIP_FILE_NAME to ${{ env.WEB_APP_NAME }} in ${{ env.RESOURCE_GROUP_NAME }}"
        
          az webapp deploy `
              --resource-group ${{ env.RESOURCE_GROUP_NAME }} `
              --name ${{ env.WEB_APP_NAME }} `
              --src-path $ZIP_FILE_NAME `
              --type zip `
              --clean true 
        env:
          FILE_NAME: "build"
          RESOURCE_GROUP_NAME: 'Dev'
          WEB_APP_NAME: 'test-web-app-43fsd32'