name: Deploy to Azure

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  DEPLOYMENT_PACKAGE_NAME: "release.zip"

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js Environment
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install Dependencies
        run: |
          yarn install
        
      - name: Build Next.js Application
        run: |
          yarn build
          mv .next/static .next/standalone/.next/static

      - name: Zip Artifact for Deployment
        run: |
          zip ${{ env.DEPLOYMENT_PACKAGE_NAME }} ./* /next -qr

      - name:  Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: ${{ env.DEPLOYMENT_PACKAGE_NAME}}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name:  Download Artifact for Deployment
        uses: actions/download-artifact@v4
        with:
          name: build

      - name: Login to Azure Subscription
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          package: ${{ env.DEPLOYMENT_PACKAGE_NAME }}
          slot-name: 'production'
