name: Deploy to Azure

on:
  push:
    branches: ["main"]
    paths:
      - 'apps/frontend/**'
      - '.github/workflows/**'
  workflow_dispatch:

env:
  DEPLOYMENT_PACKAGE_NAME: "release.zip"
  WORKSPACE_ROOT: "./apps/frontend"
  WORKSPACE_NAME: "frontend"

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: ./.github/workflows/actions/setup-node
        with:
          nohoist: true
            
      - name: Build Next.js Application
        run: |
          yarn build --filter=${{ env.WORKSPACE_NAME }}
          shopt -s dotglob
          mv -f ${{ env.WORKSPACE_ROOT }}/.next/standalone/apps/frontend/* ${{ env.WORKSPACE_ROOT }}/.next/standalone
          mkdir -p ${{ env.WORKSPACE_ROOT }}/.next/standalone/.next/static
          mv -f ${{ env.WORKSPACE_ROOT }}/.next/static/* ${{ env.WORKSPACE_ROOT }}/.next/standalone/.next/static
          rm -rf ${{ env.WORKSPACE_ROOT }}/.next/standalone/apps
          rm -rf ${{ env.WORKSPACE_ROOT }}/.next/static

      - name: Zip Artifact for Deployment
        working-directory: ${{ env.WORKSPACE_ROOT }}
        run: |
          zip ${{ env.DEPLOYMENT_PACKAGE_NAME }} ./* .next -qr

      - name:  Upload Artifact for Deployment
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: ${{ env.WORKSPACE_ROOT }}/${{ env.DEPLOYMENT_PACKAGE_NAME}}

  deploy:
    name: Deploy to Azure
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: production
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write

    steps:
      - name:  Download Artifact for Deployment
        uses: actions/download-artifact@v4
        with:
          name: artifact

      - name: Login to Azure Subscription
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.AZURE_WEB_APP_NAME }}
          package: ${{ env.DEPLOYMENT_PACKAGE_NAME }}
