name: Lint

on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Setup Node.js and install dependencies
        uses: ./.github/actions/setup-node.yaml
        with:
          node-version: 18

      - name: Run linters
        run: yarn run lint
