name: Lint

on: push

jobs:
  lint:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Setup
        uses: ./.github/workflows/templates/nodeSetup.yml

      - name: Run linters
        run: yarn run lint
